version: '3.8'

services:

  # postgresql
  postgres:
    image: postgres:latest
    container_name: db_the_market
    environment:
      POSTGRES_DB: db_the_market
      POSTGRES_USER: natutitato
      POSTGRES_PASSWORD: azujito
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  # pgadmin
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgAdmin
    environment:
      PGADMIN_DEFAULT_EMAIL: natutitato@admin.com
      PGADMIN_DEFAULT_PASSWORD: azujito
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped


# backend

  # user-service  
  user-service:
    container_name: user-service
    build:
      context: ./backend
      dockerfile: user-service/Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - postgres
  
  # product-service
  # product-service:
  #   container_name: product-service
  #   build:
  #     context: ./backend
  #     dockerfile: product-service/Dockerfile
  #   ports:
  #     - "8082:8080"
  #   depends_on:
  #     - postgres

volumes:
  postgres_data:
  pgadmin_data: